### NumPy

The goal is to make algorithm calculations in Python lighter.

In [1]:
# Import NumPy

import numpy as np

In [2]:
# Checking NumPy Version

print(np.__version__)

1.24.3


In [3]:
# Creating a NumPy array

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
# Use a tuple to create a NumPy array

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

print(type(arr)) #tidak berbentuk list karena sudah terkonversi ke NumPy

[1 2 3 4 5]
<class 'numpy.ndarray'>


TASK 1 - import numpy, chek version, make example numpy, type data

In [5]:
import numpy as np #import sekali saja sudah cukup

In [6]:
print(np.__version__)

1.24.3


In [7]:
arr = np.array([1, 3, 5, 7, 9])
print(arr)

[1 3 5 7 9]


In [8]:
import numpy as np

arr = np.array([1, 3, 5, 7, 9])

print(arr)

print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


- Dimensions in Arrays

A dimensions in arrays is one level of array depth (nested arrays).

In [ ]:
# Create a 0-D Arrays

In [11]:
# import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
# Create a 1-D Array

In [12]:
# import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
# Create a 2-D Array containing two arrays

In [13]:
# import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


TASK 2 - Making 0-D, 1-D, 2-D Array

In [14]:
# 0-D
arr = np.array(5.8)

print(arr)

print(type(arr))

5.8
<class 'numpy.ndarray'>


In [17]:
# 1-D
arr = np.array(["Data Analyst", "Kelompok 2"])

print(arr)

['Data Analyst' 'Kelompok 2']


In [16]:
# 2-D
arr = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])

print(arr)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [ ]:
# Create a 3-D array with two 2-D arrays, both containing two arrays

In [18]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# Check how many dimensions the arrays have

In [19]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim) # ndim berfungsi untuk mengetahui/mengecek jumlah dimensi pada array
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Create an array with 5 dimenions and verify that it has 5 dimensions

In [27]:
arr = np.array([1, 2, 3, 4], ndmin=5) # ndmin berfungsi untuk membuat array sesuai yang diinginkan

print(arr)
print('Number of dimensions : ', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions :  5


TASK 3 - Making multiple array dimensions, chek ndim and making a arrays with ndim

In [30]:
a = np.array(5.8)
b = np.array(["Kelompok 2"])
c = np.array([['Data Analyst'], ['MyEduSolve']])
d = np.array([[[2.5, 3.5], [4.5, 5.5]], [[6.5, 7.5], [8.5, 9.5]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [28]:
arr = np.array([1, 2, 3, 4], ndmin=4) 

print(arr)
print('Number of dimensions : ', arr.ndim)

[[[[1 2 3 4]]]]
Number of dimensions :  4


In [ ]:
# Get the first element from the following array

In [31]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
# Get the second element from the following array

In [32]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [ ]:
# Get third and fourth elements from the following array and add them

In [33]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
# Access the element on the first row, second column

In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row : ', arr[0, 1])

2nd element on 1st row :  2


In [ ]:
# Access the element on the 2nd row, 5th column

In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd row : ', arr[1, 4])

5th element on 2nd row :  10


TASK 4 - Making array 2D contents min 3 list, call (operasi math), slicing

In [42]:
# arrays 2D with 3 list
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

# Operasi penjumlahan
tambah = np.sum(arr)
print("Hasil Penjumlahan Semua Elemen : ")
print(tambah)

# Slicing untuk mengakses baris dan kolom tertentu
print('3rd element on 2nd row : ', arr[1, 2])

Hasil Penjumlahan Semua Elemen :
120
3rd element on 2nd row :  8


In [ ]:
# Access the third element of the second array of the first array

In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 0, 2])

9


In [ ]:
# Print the last element from the 2nd dim

In [39]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('Last element from 2nd dim : ', arr[1, -1])

Last element from 2nd dim :  10
